name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: |
          uv pip install --system -r pyproject.toml

      - name: Lint
        run: |
          uv pip install --system black isort
          black --check .
          isort --profile black --check .

      - name: Run Tests
        run: |
          uv pip install --system pytest pytest-asyncio
          pytest 